import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync } from "fs";
import { dirname } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const release = (process.argv[2] === "release");

// Determine output directory
const outdir = release ? "dist" : ".";
const outfile = `${outdir}/main.js`;

// Ensure output directory exists for release builds
if (release && !existsSync(outdir)) {
	mkdirSync(outdir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: (prod || release) ? false : "inline",
	treeShaking: true,
	outfile: outfile,
	minify: prod || release,
});

if (prod || release) {
	await context.rebuild();
	
	// For release builds, copy manifest.json and styles.css to dist/
	if (release) {
		console.log("Copying release assets to dist/...");
		
		// Copy manifest.json
		copyFileSync("manifest.json", `${outdir}/manifest.json`);
		console.log("  - manifest.json");
		
		// Copy styles.css if it exists
		if (existsSync("styles.css")) {
			copyFileSync("styles.css", `${outdir}/styles.css`);
			console.log("  - styles.css");
		}
		
		console.log("Release build complete!");
	}
	
	process.exit(0);
} else {
	await context.watch();
}
